### Get All Employees
get {{baseUrl}}/employees

### Add Employee
post {{baseUrl}}/employees
Content-Type: application/json

{
    "firstName": "Rod",
    "lastName": "Tolaresa"
}

### Update Employee
put {{baseUrl}}/employees
Content-Type: application/json

{
    "id": 3,
    "firstName": "Hayree"
}

### Delete Employee
delete {{baseUrl}}/employees
Content-Type: application/json

{
    "id": 5
}

### Get Employee By Id
get {{baseUrl}}/employees/2