### Get All Employees
get {{baseUrl}}/employees
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySW5mbyI6eyJ1c2VybmFtZSI6IlJvZCIsInJvbGVzIjpbMjAwMSwxOTg0LDUxNTBdfSwiaWF0IjoxNjk3ODAyMDkxLCJleHAiOjE2OTc4MDM4OTF9.x3QFZeZRnk0ize07Rqcrj3fw7d33VwSf-ykP2Q9SAAI

### Add Employee
post {{baseUrl}}/employees
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySW5mbyI6eyJ1c2VybmFtZSI6IlJvZCIsInJvbGVzIjpbMjAwMSwxOTg0LDUxNTBdfSwiaWF0IjoxNjk3ODAyMDkxLCJleHAiOjE2OTc4MDM4OTF9.x3QFZeZRnk0ize07Rqcrj3fw7d33VwSf-ykP2Q9SAAI

{
    "firstname": "Mike",
    "lastname": "Shinoda"
}

### Update Employee
put {{baseUrl}}/employees
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySW5mbyI6eyJ1c2VybmFtZSI6IlJvZCIsInJvbGVzIjpbMjAwMSwxOTg0LDUxNTBdfSwiaWF0IjoxNjk3ODAyNTU0LCJleHAiOjE2OTc4MDQzNTR9.tKivyI3shhvbun_anIWEaeqZPUrPDWcn4T_0bmuzHeo

{
    "id": "6532679085880d937db4dc75",
    "firstname": "David_updated"
}

### Delete Employee
delete {{baseUrl}}/employees
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySW5mbyI6eyJ1c2VybmFtZSI6IlJvZCIsInJvbGVzIjpbMjAwMSwxOTg0LDUxNTBdfSwiaWF0IjoxNjk3ODAyNTU0LCJleHAiOjE2OTc4MDQzNTR9.tKivyI3shhvbun_anIWEaeqZPUrPDWcn4T_0bmuzHeo

{
    "id": "653267ba85880d937db4dc77"
}

### Get Employee By Id
get {{baseUrl}}/employees/6532679085880d937db4dc75