### Get All Employees
get {{baseUrl}}/employees
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySW5mbyI6eyJ1c2VybmFtZSI6Ikl5YSJ9LCJpYXQiOjE2OTc3OTk5NDYsImV4cCI6MTY5NzgwMTc0Nn0.qjXl7QhaveVmHfnMl5OGdk-LB7wLO_LXyuQu_jWIsAk

### Add Employee
post {{baseUrl}}/employees
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySW5mbyI6eyJ1c2VybmFtZSI6Ikl5YSJ9LCJpYXQiOjE2OTc3OTk5NDYsImV4cCI6MTY5NzgwMTc0Nn0.qjXl7QhaveVmHfnMl5OGdk-LB7wLO_LXyuQu_jWIsAk

{
    "firstName": "Rod",
    "lastName": "Tolaresa"
}

### Update Employee
put {{baseUrl}}/employees
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySW5mbyI6eyJ1c2VybmFtZSI6IlJvZCIsInJvbGVzIjpbMjAwMSwxOTg0LDUxNTBdfSwiaWF0IjoxNjk3NzM2Nzc4LCJleHAiOjE2OTc3NDAzNzh9.Z85XBYJHjEXmT7Cyu6Ggw-XlNjsKVQOsdO5XeG9ifDY

{
    "id": 1,
    "firstName": "David"
}

### Delete Employee
delete {{baseUrl}}/employees
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySW5mbyI6eyJ1c2VybmFtZSI6IlJvZCIsInJvbGVzIjpbMjAwMSwxOTg0LDUxNTBdfSwiaWF0IjoxNjk3NzM2Nzc4LCJleHAiOjE2OTc3NDAzNzh9.Z85XBYJHjEXmT7Cyu6Ggw-XlNjsKVQOsdO5XeG9ifDY

{
    "id": 3
}

### Get Employee By Id
get {{baseUrl}}/employees/2