### User Creation
post {{baseUrl}}/register
Content-Type: application/json

{
    "user": "Hayree",
    "pwd": "december22"
}

### User Login
post {{baseUrl}}/auth
Content-Type: application/json

{
    "user": "Rod",
    "pwd": "password"
}

### Refresh Access Token
get {{baseUrl}}/refresh

### Logout user
get {{baseUrl}}/logout